Initialize docker
babeuloula/livre-recettes-api-v2 pull request #1
Opened 2022-11-20 11:48 UTC by Bastien2805

2022-11-20 13:20 UTC, babeuloula requested changes

2022-11-20 13:20 UTC, babeuloula commented on .env
> +# https://symfony.com/doc/current/best_practices.html#use-environment-variables-for-infrastructure-configuration
Tu peux retirer tous les commentaires, on sait comment SF fonctionne.

2022-11-20 13:20 UTC, babeuloula commented on .env
> +APP_SECRET=c5c212cbda2198313ed1ba0d0c5dd37e
Comme tu as pu le voir, j'ai mis un truc pour checker les problèmes de sécurité. C'est notamment ce secret qui l'ennui. Si tu mets ça, il ne va plus rien dire.

```suggestion
APP_SECRET=fake_secret
```

2022-11-20 13:20 UTC, babeuloula commented on .env
> +# DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=8&charset=utf8mb4"
Là aussi, tu peux les supprimer.

2022-11-20 13:20 UTC, babeuloula commented on .env
> +DATABASE_URL="postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=14&charset=utf8"
Tu veux mettre du Postgre ou c'est juste les infos de bases ?

2022-11-20 13:20 UTC, babeuloula commented on .env.test
> +APP_SECRET='$ecretf0rt3st'
```suggestion
APP_SECRET=fake_test_secret
```

2022-11-20 13:20 UTC, babeuloula commented on .env.test
> +PANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots
Dans un premier temps, comme nous n'avons pas de front, pas besoin de mettre panther.

2022-11-20 13:20 UTC, babeuloula commented on .gitignore
> +.idea
A mettre dans ton gitignore global.

2022-11-20 13:20 UTC, babeuloula commented on Makefile
> +		    rm -rf var/cache/test/vault; \
On a vault dedans ?

2022-11-20 13:20 UTC, babeuloula commented on Makefile
> +		    rm -rf public/test; \
Ce dossier sert à quoi ?

2022-11-20 13:20 UTC, babeuloula commented on Makefile
> +		--exclude src/Security/Guard/LdapAuthenticator.php
On a ça nous ?

2022-11-20 13:20 UTC, babeuloula commented on bin/phpunit
> +}
Je préfère qu'on utilise directement dans vendor/bin/simple-phpunit.

2022-11-20 13:20 UTC, babeuloula commented on composer.json
> +    "license": "proprietary",
Comme on est en open source, on va rajouter la licence [Creative Communs v3](https://creativecommons.org/licenses/by/3.0/deed.fr) Je te laisse regarder ce qu'elle contient et permet.

2022-11-20 13:20 UTC, babeuloula commented on composer.json
> +        "ext-exif": "*",
On va s'en servir ?

2022-11-20 13:20 UTC, babeuloula commented on composer.json
> +        "api-platform/core": "^2.6",
On utilise pas la v3 ?

2022-11-20 13:20 UTC, babeuloula commented on composer.json
> +        "league/csv": "^9.8",
On va s'en servir ?

2022-11-20 13:20 UTC, babeuloula commented on config/packages/monolog.yaml
> +                path: php://stderr
En prod, dans un premier temps, nous allons mettre les logs en filesystem.

2022-11-20 13:20 UTC, babeuloula commented on config/packages/monolog.yaml
> +                path: php://stderr
Idem.

2022-11-20 13:20 UTC, babeuloula commented on config/services.yaml
> +  api.prefix: '%env(API_PREFIX)%'
Vu que tu l'as, autant s'en servir dans le fichier de config d'APIP.

2022-11-20 13:20 UTC, babeuloula commented on docker-compose.yml
> +###> doctrine/doctrine-bundle ###
La même.

2022-11-20 13:20 UTC, babeuloula commented on docker-compose.override.yml
> +version: '3'
Comme on a déjà les infos dans le dossier docker, pas la peine d'avoir ce fichier.

2022-11-20 13:20 UTC, babeuloula commented on docker/php/Dockerfile
> +ARG DOCKER_PHP_EXT=1.5.14
```suggestion
ARG DOCKER_PHP_EXT=1.5.47
```

2022-11-20 13:55 UTC, Bastien2805 commented on .env
> +DATABASE_URL="postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=14&charset=utf8"
Ce sont des informations de base ouais, tu préfères que j'initialise avec mysql direct ?

2022-11-20 13:56 UTC, Bastien2805 commented on Makefile
> +		    rm -rf var/cache/test/vault; \
Oups, reste de c/c, je l'ai enlevé

2022-11-20 13:57 UTC, babeuloula commented on .env
> +DATABASE_URL="postgresql://app:!ChangeMe!@127.0.0.1:5432/app?serverVersion=14&charset=utf8"
Tant cas faire, comme tu as le docker tout prêt oui

2022-11-20 21:08 UTC, babeuloula requested changes

2022-11-20 21:08 UTC, babeuloula commented on config/packages/doctrine.yaml
> +        server_version: 'mariadb-10.5.10'
Tant cas faire, utilise la dernière version de mariadb. Regarde sur docker hub pour avoir la dernière et mets a jour aussi le docker-compose

2022-11-20 21:08 UTC, babeuloula commented on docker-compose.yml
> +version: '3'
Ce fichier n'est pas utile comme on a déjà un dossier docker.

2022-12-17 19:04 UTC, Bastien2805 commented
Bon du coup j'ai une erreur à cause du Kernel que je n'arrive pas à résoudre.. @babeuloula est-ce que tu pourrais checkout sur ma branch et checker ce qui se passe quand tu auras un peu de temps pour ça stp ?

2022-12-17 19:05 UTC, babeuloula commented
> Bon du coup j'ai une erreur à cause du Kernel que je n'arrive pas à résoudre.. @babeuloula est-ce que tu pourrais checkout sur ma branch et checker ce qui se passe quand tu auras un peu de temps pour ça stp ?

Je check ça ce weekend ou sinon lundi

2022-12-18 10:20 UTC, Bastien2805 commented
Bon j'ai trouvé d'ou venait l'erreur c'était à cause de mon routes.yaml, c'est corrigé par contre je cherches maintenant à ce que ça m'affiche autre chose qu'une page blanche quand je vais sur l'URL du projet :smile:

2022-12-18 10:33 UTC, babeuloula approved these changes

2022-12-18 10:34 UTC, merged